#!/bin/sh

#edit and uncomment the following line if you are a pigmeo developer and want to run it without installing the libraries into the GAC
#export MONO_PATH="/home/path/to/pigmeo/output/binaries/GAC"

MONO_THEME="clearlooks" mono [PIGMEO_INSTALLATION_PATH]/output/binaries/pigmeo-compiler.exe "$@"
