	; ========================================================================================
	; Assembly language file automatically generated by Pigmeo Compiler 0.0.1-svn
	; Visit http://pigmeo.org/ for more information
	; 
	; Original file: example001.exe
	; Saved to: example001.asm
	; domingo, 13 de abril de 2008 13:25:03
	; ========================================================================================

INCLUDE p16f716.inc
PROCESSOR PIC16F716

foo EQU 0x00
PORTA EQU 0x05

	ORG 0x00
	GOTO Main
	ORG 0x04	;interruption vector
	GOTO EndOfApp	;Interruptions not implemented

Main
Main_I0	MOVF PORTA,0	;ldsfld
	MOVWF foo	;stsfld
Main_I2	INCF foo,1	;ldsfld uint8, ldc.*, add, conv.u1, stsfld uint8
Main_I7	GOTO Main_I2	;br.s


EndOfApp	GOTO EndOfApp	;The application has ended, do nothing

END

